{ Bluecave Layer to Common Compiler Directives Include file
  ===========================================================================
  Created: 2001-07-11 (yyyy-mm-dd)
  ===========================================================================

  The contents of this file are subject to the Bluecave Public License V 1.0
  (the "License"). You may not copy or use this file, in either source code
  or executable form, except in compliance with the License. You may obtain
  a copy of the License at http://www.bluecave.net/licenses/.

  Software distributed under the License is distributed on an "AS IS" basis,
  WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
  for the specific language governing rights and limitations under the
  License.

  Copyright (C) 2001-2003 Bluecave Software. All Rights Reserved.
  http://www.bluecave.net/

  Copyright (C) 2001-2003 Jouni Airaksinen. All Rights Reserved.
  http://www.bluecave.net/mintus/ -- Mintus@Codefield.com

  ===========================================================================

  Unit description:

    Layer to Common Compiler directives. You can use this to change globally.
    version which is used. No need to change every source file to match new
    version of BcDirectivesXX.inc. Why this way.. well, multiple versions
    can co-exists this way.

  =========================================================================== }

{$I BcDirectives12.inc}